channels:
  - cadquery
  - conda-forge

dependencies:
  - bzip2
  - cadquery
  - cairo
  - numpy
  - click
  - click-log
  - click-plugins
  - pip:
    - affine
    - jupyter-cadquery
    - jupyter-cadquery-widgets
